### PR TITLE
Fix environment file path into readme.md

### PR DESCRIPTION
**Pull request by maximebeaudoin**

### CODE REVIEW

**Comment by jesseobrien** [comment]
This needs to be merged. I just messed around trying to use `env_path` for like 20 minutes.

**Comment by maximebeaudoin** [comment]
@JesseObrien same for me, this is why i have create this PR but @arisro doesn't seem to be active since July

**Comment by jesseobrien** [comment]
@maximebeaudoin did you get the file to actually load? Even with the `env_file` option defined, I still can't get it to load properly.

**Comment by maximebeaudoin** [comment]
@JesseObrien Yep everything work fine for me. However, i use the same .env file then the base application.

Here my current behat.yml file

``` yml
default:
    extensions:
        Arisro\Behat\ServiceContainer\LumenExtension:
            env_file: .env
        Behat\MinkExtension:
            default_session: lumen
            lumen: ~

    suites:
        home:
            paths: [ %paths.base%/features/home ]
```

**Comment by jesseobrien** [comment]
Ah okay. Thanks. I'm trying to use `.env.behat` and it's not loading. What this extension does is boot up Lumen (which by default uses the `.env.` file. It ignores the env_file variable entirely.

**Comment by arisro** [comment]
Hey!
Sorry for the troubles caused and thank you for taking your time with this PR. :)

Cheers.

**Pull request merged**
